trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    restoreNugetPackages: true
